DROP TABLE IF EXISTS PASSWORD_RESET_OTPS, TEACHER_COURSE, REGISTRATION, DONATION, COURSE_INSTRUCTORS, USER_ROLE, USERS, ROLES, COURSES;

-- USERS TABLE, UID ATM IS JUST INT THAT AUTO-INCREMENTS, CAN CHANGE LATER ACCORDING TO SPEC
CREATE TABLE USERS (
  UID INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(100) NOT NULL,
  MIDDLENAME VARCHAR(100),
  LASTNAME VARCHAR(100) NOT NULL,
  DOB DATE,
  EMAIL VARCHAR(100) UNIQUE,
  PHONENUMBER VARCHAR(10),
  ADDRESS VARCHAR(100),
  CITY VARCHAR(25),
  PROVINCE VARCHAR(2),
  POSTALCODE VARCHAR(6),
  PASSWORD VARCHAR(255) NOT NULL
);


CREATE TABLE ROLES (
  ROLEID INT PRIMARY KEY AUTO_INCREMENT,
  ROLENAME VARCHAR(25) NOT NULL
);
-- COURSES TABLE
CREATE TABLE COURSES (
  COURSEID INT PRIMARY KEY AUTO_INCREMENT,
  TITLE VARCHAR(100),
  STARTDATE DATETIME NOT NULL,
  ENDDATE DATETIME NOT NULL,
  SCHEDULE TEXT,
  LOCATION VARCHAR(100)
);

-- TEACHER_COURSE TABLE (JUNCTION FOR TEACHERS AND COURSES)
CREATE TABLE TEACHER_COURSE (
  COURSEID INT NOT NULL,
  UID INT NOT NULL,
  PRIMARY KEY (COURSEID, UID),
  FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE,
  FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE
);

-- DONATION TABLE
CREATE TABLE DONATION (
  CID INT PRIMARY KEY AUTO_INCREMENT,
  EMAIL VARCHAR(100),
  AMOUNT DECIMAL(10,2),
  PROVIDER VARCHAR(100)
);

-- JUNCTION TABLES

-- REGISTRATION
CREATE TABLE REGISTRATION (
  UID INT,
  COURSEID INT,
  PRIMARY KEY (UID, COURSEID),
  FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE,
  FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE
);

-- USER_ROLES JUNCTION TABLE
CREATE TABLE USER_ROLE (
  UID INT,
  ROLEID INT,
  PRIMARY KEY (UID, ROLEID),
  FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE,
  FOREIGN KEY (ROLEID) REFERENCES ROLES(ROLEID) ON DELETE CASCADE
);

CREATE TABLE COURSE_INSTRUCTORS (
  COURSEID INT NOT NULL,
  UID INT NOT NULL,
  PRIMARY KEY (COURSEID, UID),
  FOREIGN KEY (COURSEID) REFERENCES COURSES(COURSEID) ON DELETE CASCADE,
  FOREIGN KEY (UID) REFERENCES USERS(UID) ON DELETE CASCADE
);

CREATE TABLE PASSWORD_RESET_OTPS (
  ID INT PRIMARY KEY AUTO_INCREMENT,
  UID INT NOT NULL,
  OTP VARCHAR(10) NOT NULL,
  EXPIRESAT DATETIME NOT NULL,
  USED BOOLEAN DEFAULT FALSE,
  CREATEDAT DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USERS (FIRSTNAME, MIDDLENAME, LASTNAME, DOB, EMAIL, PASSWORD, PHONENUMBER, ADDRESS, CITY, PROVINCE, POSTALCODE)
VALUES 
('Ali', 'Ahmed', 'Khan', '1990-04-20', 'ali.khan@example.com', '$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045551234', '123 Main St', 'Vancouver', 'BC', 'V5K0A1'),
('Ubada', NULL, 'Raja', '1995-09-15', 'ubada.r@example.com','$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045555678', '456 Oak Ave', 'Burnaby', 'BC', 'V5C2Z4'),
('Yusuf', 'Ibrahim', 'Ali', '2000-01-05', 'yusuf.s@example.com', '$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045559876', '789 Pine Rd', 'Surrey', 'BC', 'V3T3W2'),
('Hamza', 'Omar', 'Siddiqui', '1997-07-18', 'hamza.s@example.com','$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045551122', '159 Maple St', 'Surrey', 'BC', 'V3W5N9'),
('Khalid', NULL, 'Hussein', '1992-02-25', 'khalid.h@example.com','$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045553344', '753 Birch Ave', 'Burnaby', 'BC', 'V5A3L7'),
('Imran', 'Yusuf', 'Malik', '1989-10-03', 'imran.m@example.com','$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045555566', '852 Willow Rd', 'Vancouver', 'BC', 'V5Z2M3'),
('Zaid', NULL, 'Qureshi', '2001-12-29', 'zaid.q@example.com', '$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045557788', '456 Aspen Dr', 'Delta', 'BC', 'V4C4X2'),
('Adnan', 'Ibrahim', 'Farooq', '1995-04-14', 'adnan.f@example.com', '$2a$12$t.dfg8H85VmdBrlXF2IK4uiE5PfyZYyc3hP83F4vbeCD4tWpRB1eS', '6045559900', '963 Oak Crescent', 'Richmond', 'BC', 'V6Y3G4');

INSERT INTO COURSES (TITLE, STARTDATE, ENDDATE, SCHEDULE, LOCATION)
VALUES 
('Quran Memorization Class', '2025-07-01 18:00:00', '2025-09-30 20:00:00', 'Monday, Wednesday', 'Masjid Hall'),
('Beginner Arabic Workshop', '2025-07-10 17:00:00', '2025-08-25 19:00:00', 'Tuesday, Thursday', 'Community Center Room B'),
('Summer Youth Camp', '2025-08-05 09:00:00', '2025-08-20 12:00:00', 'Monday, Tuesday, Wednesday, Thursday, Friday', 'Zoom');

INSERT INTO ROLES (ROLENAME) VALUES
('Admin'),
('Instructor'),
('Parent'),
('Student'),
('Donor');

INSERT INTO USER_ROLE (UID, ROLEID)
VALUES
(2, 2),
(1, 4),
(3, 4),
(5, 1),
(6, 3);


